### ISSUE TITLE
Switch to PHP 8.0

### ISSUE THREAD

**Issue by JPustkuchen** [webksde/ddev-vscode-devcontainer-drupal9-template#104] opened 2022-06-24 15:16 UTC
PHP 7.4 will be EOL end of 2022. We should switch to 8.0 sooner or later.

https://www.php.net/supported-versions.php

**Comment by joshsedl** [comment] 2022-06-27 12:58
Duplicate of https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/issues/56

**Closed by joshsedl** 2022-06-27 12:58 UTC
Labels: priority-low, plan
